import { KumaRegistry } from '@kuma-ui/next-plugin/registry';
import type { Metadata } from 'next';
import { Analytics } from '@vercel/analytics/react';
import './globals.css';
import { SpeedInsights } from '@vercel/speed-insights/react';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Analytics />
				<SpeedInsights />
				<KumaRegistry>{children}</KumaRegistry>
			</body>
		</html>
	);
}
